name: CI

on: push

env:
  MIX_ENV: test

jobs:
  compile:
    name: Compile

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x
      - uses: actions/cache@v1
        id: cache-mix
        with:
          path: deps
          key: ${{ runner.os }}-mix-v5-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-v5-
      - uses: actions/cache@v1
        id: cache-build
        with:
          path: _build
          key: ${{ runner.os }}-build-v3-${{ hashFiles('lib/**/*.ex') }}${{ hashFiles('test/**/*.ex') }}${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-v3-
      - name: Install dependencies
        if: steps.cache-mix.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: Compile
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: mix compile --warnings-as-errors

  format:
    name: "Check Formatted"

    needs: compile

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-v5-${{ hashFiles('mix.lock') }}
      - name: Check formatted
        run: mix format --check-formatted

  test:
    name: Tests

    needs: compile

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-v5-${{ hashFiles('mix.lock') }}
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-v3-${{ hashFiles('lib/**/*.ex') }}${{ hashFiles('test/**/*.ex') }}${{ hashFiles('mix.lock') }}
      - name: Run tests
        run: mix coveralls.json
        env:
          DATABASE_URL: ecto://postgres@localhost/ecto_diff_test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true

  credo:
    name: Credo

    needs: compile

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-v5-${{ hashFiles('mix.lock') }}
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-v3-${{ hashFiles('lib/**/*.ex') }}${{ hashFiles('test/**/*.ex') }}${{ hashFiles('mix.lock') }}
      - name: Run credo
        run: mix credo --strict

  dialyzer:
    name: Dialyzer

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x
      - uses: actions/cache@v1
        id: cache-build-dev
        with:
          path: _build
          key: ${{ runner.os }}-build-dev-v3-${{ hashFiles('lib/**/*.ex') }}${{ hashFiles('test/**/*.ex') }}${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-dev-v3-
      - uses: actions/cache@v1
        with:
          path: plts
          key: ${{ runner.os }}-plts-v3-${{ hashFiles('lib/**/*.ex') }}${{ hashFiles('test/**/*.ex') }}${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-plts-v3-
      - name: Install dependencies
        run: mix deps.get
      - name: Compile
        if: steps.cache-build-dev.outputs.cache-hit != 'true'
        run: mix compile
      - name: Run dialyzer
        run: mix dialyzer
